"use client";
import { useState } from "react";
import { Check, ChevronLeft, ChevronRight, Cpu, Globe2, Rocket, ServerIcon, Sparkles, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const steps=["Welcome","Create server","Choose version","Choose loader","RAM","World","Review","Launch"];
export function ServerWizard(){
  const [step,setStep]=useState(0);
  const [data,setData]=useState({name:"My Minecraft Server",version:"1.21.1",loader:"Paper",ram:"8",seed:"",difficulty:"normal"});
  const set=(k:keyof typeof data,v:string)=>setData((d)=>({...d,[k]:v}));
  return <div className="mx-auto max-w-5xl">
    <div className="mb-7 overflow-x-auto pb-1 scrollbar-thin"><div className="grid min-w-[680px] grid-cols-8 gap-2">{steps.map((s,i)=><div key={s}><div className={`h-1 rounded-full transition-all ${i<=step?"bg-gradient-to-r from-emerald-400 to-cyan-400":"bg-white/[.07]"}`}/><p className={`mt-2 text-[10px] font-medium ${i===step?"text-white":"text-muted-foreground"}`}>{i+1}. {s}</p></div>)}</div></div>
    <Card className="overflow-hidden border-white/[.08] shadow-[0_24px_80px_rgba(0,0,0,.24)]">
      <div className="border-b border-white/[.06] bg-white/[.018] p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl border border-emerald-500/15 bg-emerald-500/[.08] text-emerald-400"><Sparkles className="size-4"/></div><div><h2 className="text-base font-semibold tracking-[-.02em]">{steps[step]}</h2><p className="mt-0.5 text-[11px] text-muted-foreground">Step {step+1} of {steps.length} · You can change these settings later</p></div></div></div>
      <div className="min-h-[390px] p-5 sm:p-7">
        {step===0&&<div className="grid min-h-[320px] place-items-center text-center"><div className="max-w-xl"><div className="mx-auto grid size-14 place-items-center rounded-2xl border border-emerald-500/15 bg-gradient-to-b from-emerald-500/10 to-cyan-500/5 text-emerald-400"><WandSparkles className="size-6"/></div><h3 className="mt-5 text-2xl font-semibold tracking-[-.035em]">Your server, configured properly from day one.</h3><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-muted-foreground">This guided setup creates an isolated Docker-backed Minecraft server with persistent storage, sensible memory limits, backups, and the loader you choose.</p><div className="mx-auto mt-6 grid max-w-lg grid-cols-3 gap-2 text-left"><MiniFact label="Isolated" value="Docker"/><MiniFact label="Persistent" value="World data"/><MiniFact label="Managed" value="Backups"/></div></div></div>}
        {step===1&&<div className="max-w-xl space-y-5"><div><h3 className="text-lg font-semibold">Name this server</h3><p className="mt-1.5 text-sm leading-6 text-muted-foreground">Use something recognizable in your server switcher and activity logs.</p></div><label className="block space-y-2"><span className="text-[11px] font-semibold text-muted-foreground">Server name</span><Input value={data.name} onChange={(e)=>set("name",e.target.value)} autoFocus className="h-11"/></label><p className="text-[11px] text-muted-foreground">Example: BetterMC Survival, Creative Build, Friends SMP</p></div>}
        {step===2&&<ChoiceSection title="Choose a Minecraft version" description="Only compatible loader and marketplace builds will be offered later."><OptionGrid values={["1.21.1","1.21","1.20.6","1.20.4"]} selected={data.version} onSelect={(v)=>set("version",v)} icon={<Globe2 className="size-5"/>}/></ChoiceSection>}
        {step===3&&<ChoiceSection title="Choose a loader" description="Paper is ideal for plugins; Fabric, Forge and NeoForge are best for modded servers."><OptionGrid values={["Vanilla","Paper","Fabric","Forge","NeoForge"]} selected={data.loader} onSelect={(v)=>set("loader",v)} icon={<ServerIcon className="size-5"/>}/></ChoiceSection>}
        {step===4&&<ChoiceSection title="Allocate memory" description="Leave enough host memory for Docker, the control panel, and filesystem cache."><OptionGrid values={["2","4","6","8","12","16"]} suffix=" GB" selected={data.ram} onSelect={(v)=>set("ram",v)} icon={<Cpu className="size-5"/>}/></ChoiceSection>}
        {step===5&&<div className="max-w-2xl"><h3 className="text-lg font-semibold">World configuration</h3><p className="mt-1.5 text-sm text-muted-foreground">Start fresh with a random seed or use a known seed.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-[11px] font-semibold text-muted-foreground">World seed</span><Input value={data.seed} onChange={(e)=>set("seed",e.target.value)} placeholder="Random if empty" className="h-11"/></label><label className="space-y-2"><span className="text-[11px] font-semibold text-muted-foreground">Difficulty</span><select value={data.difficulty} onChange={(e)=>set("difficulty",e.target.value)} className="h-11 w-full rounded-xl border border-white/[.08] bg-black/20 px-3 text-sm outline-none focus:ring-2 focus:ring-primary/60"><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select></label></div></div>}
        {step===6&&<div><div className="mb-5"><h3 className="text-lg font-semibold">Review configuration</h3><p className="mt-1.5 text-sm text-muted-foreground">Everything below can be changed later, though loader changes may require reinstalling the runtime.</p></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{Object.entries(data).map(([k,v])=><div key={k} className="rounded-2xl border border-white/[.065] bg-white/[.018] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-muted-foreground">{k}</p><p className="mt-2 text-sm font-medium">{v||"Random"}{k==="ram"?" GB":""}</p></div>)}</div></div>}
        {step===7&&<div className="grid min-h-[320px] place-items-center text-center"><div className="max-w-lg"><div className="mx-auto grid size-14 place-items-center rounded-2xl border border-emerald-500/20 bg-emerald-500/10 text-emerald-400"><Rocket className="size-6"/></div><h3 className="mt-5 text-2xl font-semibold tracking-[-.035em]">Ready to launch {data.name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">MCPanel will create the persistent directories, provision the container, apply the selected runtime, and bring the server online. Initial boot can take a little longer while Minecraft downloads its server files.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-white/[.07] bg-white/[.025] px-3 py-1.5 text-[11px] text-muted-foreground"><span className="size-1.5 rounded-full bg-emerald-400"/>{data.version} · {data.loader} · {data.ram} GB</div></div></div>}
      </div>
      <div className="flex items-center justify-between border-t border-white/[.06] bg-white/[.012] p-4 sm:px-6"><Button variant="ghost" disabled={step===0} onClick={()=>setStep((s)=>s-1)}><ChevronLeft className="size-4"/>Back</Button><span className="hidden text-[10px] text-muted-foreground sm:block">Your changes are kept while you move between steps.</span>{step<7?<Button onClick={()=>setStep((s)=>s+1)}>{step===0?"Get started":"Continue"}<ChevronRight className="size-4"/></Button>:<Button><Check className="size-4"/>Launch server</Button>}</div>
    </Card>
  </div>
}
function ChoiceSection({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div><h3 className="text-lg font-semibold">{title}</h3><p className="mt-1.5 mb-6 text-sm text-muted-foreground">{description}</p>{children}</div>}
function MiniFact({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.06] bg-white/[.018] p-3"><p className="text-[9px] uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-1 text-xs font-medium">{value}</p></div>}
function OptionGrid({values,selected,onSelect,icon,suffix=""}:{values:string[];selected:string;onSelect:(v:string)=>void;icon:React.ReactNode;suffix?:string}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{values.map((v)=><button key={v} onClick={()=>onSelect(v)} className={`group rounded-2xl border p-4 text-left outline-none transition duration-150 focus-visible:ring-2 focus-visible:ring-primary/60 ${selected===v?"border-emerald-500/35 bg-emerald-500/[.065] shadow-[inset_0_0_0_1px_rgba(52,211,153,.04)]":"border-white/[.065] bg-white/[.018] hover:border-white/[.1] hover:bg-white/[.035]"}`}><div className={`mb-5 grid size-9 place-items-center rounded-xl border transition ${selected===v?"border-emerald-500/20 bg-emerald-500/10 text-emerald-400":"border-white/[.055] bg-white/[.02] text-muted-foreground group-hover:text-foreground"}`}>{icon}</div><div className="flex items-center justify-between gap-2"><p className="font-medium">{v}{suffix}</p>{selected===v?<Check className="size-4 text-emerald-400"/>:null}</div><p className="mt-1 text-[10px] text-muted-foreground">Production-ready configuration</p></button>)}</div>}
