"use client";
import Link from "next/link";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { ChevronDown, Copy, LogOut, Play, Plus, Power, RotateCw, Search, ServerIcon, Settings, ShieldCheck, UserCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { NotificationMenu } from "@/components/product/product-layer";
import { useServerStore } from "@/lib/stores/server-store";

export function Header(){
  const {server,busy,runAction}=useServerStore();
  const copy=()=>{navigator.clipboard?.writeText(server.ip);window.dispatchEvent(new CustomEvent("mcpanel:toast",{detail:{title:"Server address copied",description:server.ip,tone:"success"}}));};
  return <header className="sticky top-0 z-40 border-b border-white/[.065] bg-background/82 backdrop-blur-2xl supports-[backdrop-filter]:bg-background/72"><div className="flex min-h-[68px] items-center gap-2 px-4 sm:px-6 lg:px-8">
    <button className="flex min-w-0 items-center gap-2.5 rounded-xl border border-white/[.07] bg-white/[.025] px-3 py-2 text-sm transition hover:bg-white/[.05] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/70"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-emerald-500/10"><ServerIcon className="size-3.5 text-emerald-400"/></span><span className="hidden max-w-40 truncate font-medium sm:block">{server.name}</span><ChevronDown className="size-3.5 shrink-0 text-muted-foreground"/></button>
    <Badge className="hidden gap-1.5 border-emerald-500/20 bg-emerald-500/10 text-emerald-300 sm:flex"><span className="size-1.5 rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,.7)]"/>{server.status}</Badge>
    <button onClick={()=>window.dispatchEvent(new CustomEvent("mcpanel:palette"))} className="ml-1 hidden h-9 min-w-[230px] items-center gap-2 rounded-xl border border-white/[.07] bg-white/[.022] px-3 text-left text-xs text-muted-foreground transition hover:bg-white/[.045] hover:text-foreground md:flex"><Search className="size-3.5"/><span className="flex-1">Search panel</span><kbd className="rounded border border-white/10 bg-white/[.035] px-1.5 py-0.5 text-[9px]">⌘K</kbd></button>
    <div className="hidden items-center gap-2 text-[11px] text-muted-foreground xl:flex"><span className="ml-2">{server.ip}</span><button onClick={copy} className="rounded-md p-1 hover:bg-white/5 hover:text-white" title="Copy IP"><Copy className="size-3.5"/></button><span className="text-white/15">·</span><span>{server.version}</span><span className="text-white/15">·</span><span>{server.loader}</span></div>
    <div className="ml-auto flex items-center gap-1.5"><div className="hidden items-center gap-1.5 xl:flex"><Button variant="outline" size="sm" disabled={busy||server.status==="online"} onClick={()=>runAction("start")}><Play className="size-3.5"/>Start</Button><Button variant="outline" size="sm" disabled={busy||server.status==="offline"} onClick={()=>runAction("restart")}><RotateCw className="size-3.5"/>Restart</Button><Button variant="outline" size="sm" disabled={busy||server.status==="offline"} onClick={()=>runAction("stop")}><Power className="size-3.5"/>Stop</Button></div><button onClick={()=>window.dispatchEvent(new CustomEvent("mcpanel:palette"))} className="grid size-9 place-items-center rounded-lg border border-white/[.07] bg-white/[.025] text-muted-foreground md:hidden" aria-label="Search"><Search className="size-4"/></button><NotificationMenu/><Link href="/servers/new"><Button variant="secondary" size="icon" title="Create server"><Plus className="size-4"/></Button></Link>
      <DropdownMenu.Root><DropdownMenu.Trigger asChild><button className="grid size-9 place-items-center rounded-full border border-white/[.08] bg-gradient-to-b from-white/[.08] to-white/[.035] text-muted-foreground transition hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/70" aria-label="Open account menu"><UserCircle2 className="size-5"/></button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content align="end" sideOffset={10} className="z-[70] w-56 rounded-xl border border-white/10 bg-[#0d1016]/98 p-1.5 shadow-2xl"><div className="px-2.5 py-2"><p className="text-sm font-medium">Owner account</p><p className="mt-0.5 text-[11px] text-muted-foreground">Full administrative access</p></div><DropdownMenu.Separator className="my-1 h-px bg-white/[.07]"/><DropdownMenu.Item asChild><Link href="/settings/security" className="flex cursor-default items-center gap-2 rounded-lg px-2.5 py-2 text-xs outline-none hover:bg-white/[.05]"><ShieldCheck className="size-3.5"/>Security</Link></DropdownMenu.Item><DropdownMenu.Item asChild><Link href="/settings" className="flex cursor-default items-center gap-2 rounded-lg px-2.5 py-2 text-xs outline-none hover:bg-white/[.05]"><Settings className="size-3.5"/>Settings</Link></DropdownMenu.Item><DropdownMenu.Separator className="my-1 h-px bg-white/[.07]"/><DropdownMenu.Item className="flex cursor-default items-center gap-2 rounded-lg px-2.5 py-2 text-xs text-red-300 outline-none hover:bg-red-500/10"><LogOut className="size-3.5"/>Sign out</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>
    </div>
  </div></header>
}
