"use client";
import Image from "next/image";
import { useEffect,useMemo,useState } from "react";
import { AlertTriangle, CheckCircle2, Download, Loader2, PackageCheck, RefreshCw, Search, ToggleLeft, ToggleRight, Trash2, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { modsApi, type BrowseMod, type InstallPlan, type InstalledModDto } from "@/lib/api/mods";
import { useServerStore } from "@/lib/stores/server-store";

type Tab="browse"|"installed"|"updates";
const categories=["", "adventure", "cursed", "decoration", "economy", "equipment", "food", "library", "magic", "management", "minigame", "mobs", "optimization", "social", "storage", "technology", "transportation", "utility", "worldgen"];
export function ModrinthMods(){
 const server=useServerStore(s=>s.server); const [tab,setTab]=useState<Tab>("browse"); const [q,setQ]=useState("");
 const [loader,setLoader]=useState(server.loader); const [version,setVersion]=useState(server.version); const [category,setCategory]=useState("");
 const [browse,setBrowse]=useState<BrowseMod[]>([]); const [installed,setInstalled]=useState<InstalledModDto[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null);
 const [plan,setPlan]=useState<InstallPlan|null>(null); const [selected,setSelected]=useState<BrowseMod|null>(null); const [optionals,setOptionals]=useState<Set<string>>(new Set());
 const refreshInstalled=async()=>{const r=await modsApi.installed(server.id);setInstalled(r.mods)};
 useEffect(()=>{refreshInstalled().catch(e=>setError(message(e)))},[server.id]);
 useEffect(()=>{if(tab!=="browse")return; const timer=setTimeout(async()=>{setLoading(true);setError(null);try{const r=await modsApi.search(server.id,{q,minecraftVersion:version,loader,category,limit:24});setBrowse(r.items)}catch(e){setError(message(e))}finally{setLoading(false)}},300);return()=>clearTimeout(timer)},[server.id,tab,q,version,loader,category]);
 const visibleInstalled=useMemo(()=>tab==="updates"?installed.filter(m=>m.updateAvailable):installed,[installed,tab]);
 const openPlan=async(item:BrowseMod)=>{if(!item.latestCompatibleVersion){setError(`No ${loader} build for Minecraft ${version}.`);return}setBusy(item.projectId);setError(null);try{const p=await modsApi.plan(server.id,item.projectId,item.latestCompatibleVersion.id);setSelected(item);setPlan(p);setOptionals(new Set())}catch(e){setError(message(e))}finally{setBusy(null)}};
 const install=async()=>{if(!selected||!plan)return;setBusy(selected.projectId);try{await modsApi.install(server.id,{projectId:selected.projectId,versionId:plan.versionId,optionalDependencyProjectIds:[...optionals]});setPlan(null);setSelected(null);await refreshInstalled();setTab("installed")}catch(e){setError(message(e))}finally{setBusy(null)}};
 const updateOne=async(mod:InstalledModDto)=>{setBusy(mod.id);try{await modsApi.update(server.id,mod.id);await refreshInstalled()}catch(e){setError(message(e))}finally{setBusy(null)}};
 const remove=async(mod:InstalledModDto)=>{setBusy(mod.id);try{await modsApi.remove(server.id,mod.id);await refreshInstalled()}catch(e){setError(message(e))}finally{setBusy(null)}};
 const toggle=async(mod:InstalledModDto)=>{setBusy(mod.id);try{await modsApi.setEnabled(server.id,mod.id,!mod.enabled);await refreshInstalled()}catch(e){setError(message(e))}finally{setBusy(null)}};
 const updateAll=async()=>{setBusy("all");try{await modsApi.updateAll(server.id);await refreshInstalled()}catch(e){setError(message(e))}finally{setBusy(null)}};
 return <>
  <div className="mb-4 flex flex-col gap-3 xl:flex-row xl:items-center"><div className="inline-flex w-fit rounded-lg border bg-white/[.02] p-1">{(["browse","installed","updates"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-md px-3 py-1.5 text-sm capitalize ${tab===t?"bg-white/[.08] text-white":"text-muted-foreground"}`}>{t==="updates"?`Updates Available${installed.filter(m=>m.updateAvailable).length?` (${installed.filter(m=>m.updateAvailable).length})`:""}`:t}</button>)}</div>{tab==="browse"?<><div className="relative min-w-64 xl:ml-auto"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Modrinth mods…"/></div><Select value={version} onChange={setVersion} options={[server.version,"1.21.4","1.21.1","1.20.6","1.20.1"]}/><Select value={loader} onChange={setLoader} options={["Fabric","Forge","NeoForge"]}/><Select value={category} onChange={setCategory} options={categories} label="All categories"/></>:<div className="xl:ml-auto"><Button onClick={updateAll} disabled={busy!==null}><RefreshCw className={`size-4 ${busy==="all"?"animate-spin":""}`}/>Update all</Button></div>}</div>
  {error&&<div className="mb-4 flex items-center gap-2 rounded-lg border border-red-500/20 bg-red-500/[.06] px-4 py-3 text-sm text-red-300"><AlertTriangle className="size-4"/>{error}</div>}
  {tab==="browse"?(loading?<LoadingGrid/>:<div className="grid gap-3 xl:grid-cols-2">{browse.map(item=><Card key={item.projectId} className="p-4"><div className="flex gap-4">{item.iconUrl?<Image src={item.iconUrl} alt="" width={48} height={48} className="size-12 rounded-xl border object-cover"/>:<div className="grid size-12 shrink-0 place-items-center rounded-xl border bg-white/[.04]"><PackageCheck className="size-5 text-emerald-400"/></div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{item.name}</h3>{item.latestCompatibleVersion?<Badge>{item.latestCompatibleVersion.version}</Badge>:<Badge className="border-amber-500/20 text-amber-300">No compatible build</Badge>}</div><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{item.description}</p><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-muted-foreground"><span>by {item.author}</span><span>·</span><span>{formatDownloads(item.downloads)} downloads</span>{item.categories.slice(0,2).map(c=><Badge key={c}>{c}</Badge>)}</div></div><Button size="sm" disabled={!item.latestCompatibleVersion||busy===item.projectId} onClick={()=>openPlan(item)}>{busy===item.projectId?<Loader2 className="size-3.5 animate-spin"/>:<Download className="size-3.5"/>}Install</Button></div></Card>)}</div>):<div className="grid gap-3 xl:grid-cols-2">{visibleInstalled.map(mod=><Card key={mod.id} className="p-4"><div className="flex items-center gap-4"><div className="grid size-12 shrink-0 place-items-center rounded-xl border bg-white/[.04]"><PackageCheck className="size-5 text-emerald-400"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{mod.name}</h3>{mod.version&&<Badge>v{mod.version}</Badge>}{mod.updateAvailable&&<Badge className="border-blue-500/20 bg-blue-500/10 text-blue-300">{mod.latestVersion?`Update ${mod.latestVersion}`:"Update available"}</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{mod.fileName} · {mod.source==="modrinth"?"Managed by Modrinth":"Manual install"}</p></div><div className="flex gap-1">{mod.updateAvailable&&<Button size="sm" variant="outline" disabled={busy===mod.id} onClick={()=>updateOne(mod)}><RefreshCw className={`size-3.5 ${busy===mod.id?"animate-spin":""}`}/>Update</Button>}<Button size="icon" variant="ghost" disabled={busy===mod.id} onClick={()=>toggle(mod)} title={mod.enabled?"Disable":"Enable"}>{mod.enabled?<ToggleRight className="size-5 text-emerald-400"/>:<ToggleLeft className="size-5"/>}</Button><Button size="icon" variant="ghost" disabled={busy===mod.id} onClick={()=>remove(mod)} title="Uninstall"><Trash2 className="size-4"/></Button></div></div></Card>)}</div>}
  {!loading&&((tab==="browse"&&browse.length===0)||(tab!=="browse"&&visibleInstalled.length===0))&&<div className="rounded-xl border border-dashed p-12 text-center text-sm text-muted-foreground">{tab==="updates"?"Everything is up to date.":`No mods found in ${tab}.`}</div>}
  {plan&&selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" onMouseDown={()=>{setPlan(null);setSelected(null)}}><Card className="max-h-[85vh] w-full max-w-2xl overflow-auto p-0" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Install {selected.name}</h2><p className="text-xs text-muted-foreground">{plan.version} · dependency review</p></div><Button size="icon" variant="ghost" onClick={()=>{setPlan(null);setSelected(null)}}><X className="size-4"/></Button></div><div className="space-y-3 p-5">{plan.dependencies.length===0?<div className="flex items-center gap-2 text-sm text-muted-foreground"><CheckCircle2 className="size-4 text-emerald-400"/>No external dependencies.</div>:plan.dependencies.map((dep,i)=><label key={`${dep.projectId}-${i}`} className={`flex gap-3 rounded-lg border p-3 ${!dep.compatible?"border-amber-500/20 bg-amber-500/[.04]":""}`}><input type="checkbox" className="mt-1" checked={dep.type==="required"||Boolean(dep.projectId&&optionals.has(dep.projectId))} disabled={dep.type!=="optional"||!dep.compatible||dep.alreadyInstalled} onChange={()=>{if(!dep.projectId)return;setOptionals(prev=>{const next=new Set(prev);next.has(dep.projectId!)?next.delete(dep.projectId!):next.add(dep.projectId!);return next})}}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{dep.name}</span><Badge className={dep.type==="required"?"text-emerald-300":dep.type==="incompatible"?"text-red-300":"text-blue-300"}>{dep.type}</Badge>{dep.alreadyInstalled&&<Badge>installed</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{dep.compatible?(dep.selectedVersion?`Compatible version ${dep.selectedVersion}`:"Compatible"):dep.reason}</p></div></label>)}{plan.warnings.map(w=><div key={w} className="flex gap-2 rounded-lg bg-amber-500/[.06] p-3 text-xs text-amber-200"><AlertTriangle className="size-4 shrink-0"/>{w}</div>)}</div><div className="flex justify-end gap-2 border-t p-5"><Button variant="outline" onClick={()=>{setPlan(null);setSelected(null)}}>Cancel</Button><Button disabled={!plan.canInstall||busy===selected.projectId} onClick={install}>{busy===selected.projectId?<Loader2 className="size-4 animate-spin"/>:<Download className="size-4"/>}Install compatible mods</Button></div></Card></div>}
 </>
}
function Select({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label?:string}){return <select value={value} onChange={e=>onChange(e.target.value)} className="h-9 rounded-md border bg-[#0d1016] px-3 text-sm text-foreground outline-none"><option value="">{label??"All"}</option>{[...new Set(options.filter(Boolean))].map(o=><option key={o} value={o}>{o}</option>)}</select>}
function LoadingGrid(){return <div className="grid gap-3 xl:grid-cols-2">{Array.from({length:6}).map((_,i)=><div key={i} className="h-28 animate-pulse rounded-xl border bg-white/[.025]"/>)}</div>}
function formatDownloads(n:number){return new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(n)}
function message(e:unknown){return e instanceof Error?e.message:"Unexpected error"}
