import { randomBytes } from 'node:crypto';
import type { User } from '@prisma/client';
import type { AppEnv } from '../config/env.js';
import { AppError, ConflictError, ForbiddenError, UnauthorizedError } from '../lib/errors.js';
import { hashPassword, verifyPassword } from '../lib/password.js';
import { base32Encode,decryptSecret,encryptSecret,hmac256,randomToken,safeEqualHex,sha256,verifyTotp } from '../lib/auth-crypto.js';
import { listPermissions,type Permission } from '../auth/permissions.js';
import type { UserRepository } from '../repositories/user-repository.js';
import type { SessionRepository } from '../repositories/session-repository.js';
export interface AuthenticatedUser{id:string;username:string;role:string;permissions:Permission[];totpEnabled:boolean;}
export class TotpRequiredError extends AppError{constructor(){super('Two-factor authentication required',401,'TOTP_REQUIRED');}}
export class AuthService{
constructor(private users:UserRepository,private sessions:SessionRepository,private env:AppEnv){}
async ensureBootstrapAdmin(){const existing=await this.users.findByUsername(this.env.ADMIN_USERNAME);if(existing)return;await this.users.upsertOwner(this.env.ADMIN_USERNAME,await hashPassword(this.env.ADMIN_PASSWORD));}
async login(username:string,password:string,totp:string|undefined,recoveryCode:string|undefined,meta:{ip?:string;userAgent?:string}){const user=await this.users.findByUsername(username);const valid=user?await verifyPassword(password,user.passwordHash):(await hashPassword(password),false);if(!user||!valid){if(user)await this.fail(user);throw new UnauthorizedError('Invalid username or password');}if(user.lockedUntil&&user.lockedUntil>new Date())throw new ForbiddenError('Account temporarily locked');if(user.totpEnabled&&!(await this.verifySecondFactor(user,totp,recoveryCode))){await this.fail(user);throw new TotpRequiredError();}await this.users.recordSuccessfulLogin(user.id);const session=await this.createSession(user.id,meta);return{user:toPublic(user),session};}
async authenticate(rawToken:string|undefined){if(!rawToken)throw new UnauthorizedError();const s=await this.sessions.findActiveByTokenHash(sha256(rawToken),new Date());if(!s)throw new UnauthorizedError();const user=await this.users.findById(s.userId);if(!user)throw new UnauthorizedError();if(Date.now()-s.lastSeenAt.getTime()>60_000)void this.sessions.touch(s.id,new Date());return{user:toPublic(user),session:s};}
verifyCsrf(session:{csrfTokenHash:string},token:string|undefined){if(!token||!safeEqualHex(session.csrfTokenHash,sha256(token)))throw new ForbiddenError('Invalid CSRF token');}
async logout(sessionId:string,userId:string){await this.sessions.revoke(sessionId,userId);}async getUser(id:string){const u=await this.users.findById(id);return u?toPublic(u):null;}
async listSessions(userId:string,currentId:string){const rows=await this.sessions.listActiveByUser(userId,new Date());return rows.map(s=>({id:s.id,ip:s.ip,userAgent:s.userAgent,createdAt:s.createdAt,lastSeenAt:s.lastSeenAt,expiresAt:s.expiresAt,current:s.id===currentId}));}
async revokeSession(userId:string,id:string,currentId:string){if(id===currentId)throw new ConflictError('Use logout to revoke the current session');return this.sessions.revoke(id,userId);}async revokeOtherSessions(userId:string,currentId:string){return this.sessions.revokeAll(userId,currentId);}
async changePassword(userId:string,currentPassword:string,newPassword:string,currentSessionId:string){const u=await this.users.findById(userId);if(!u||!(await verifyPassword(currentPassword,u.passwordHash)))throw new UnauthorizedError('Current password is incorrect');await this.users.updatePassword(userId,await hashPassword(newPassword));await this.sessions.revokeAll(userId,currentSessionId);}
async beginTotp(userId:string){const u=await this.users.findById(userId);if(!u)throw new UnauthorizedError();const secret=base32Encode(randomBytes(20));const encrypted=encryptSecret(secret,this.env.AUTH_ENCRYPTION_KEY);await this.users.setTotp(userId,encrypted,'[]',false);const issuer=encodeURIComponent(this.env.TOTP_ISSUER),label=encodeURIComponent(`${this.env.TOTP_ISSUER}:${u.username}`);return{secret,otpauthUri:`otpauth://totp/${label}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`};}
async confirmTotp(userId:string,code:string){const u=await this.users.findById(userId);if(!u?.totpSecretEncrypted)throw new ConflictError('TOTP setup has not been started');const secret=decryptSecret(u.totpSecretEncrypted,this.env.AUTH_ENCRYPTION_KEY);if(!verifyTotp(secret,code))throw new UnauthorizedError('Invalid verification code');const recoveryCodes=Array.from({length:10},()=>`${randomToken(6)}-${randomToken(6)}`);const hashes=recoveryCodes.map(c=>hmac256(this.env.AUTH_RECOVERY_PEPPER,c));await this.users.setTotp(userId,u.totpSecretEncrypted,JSON.stringify(hashes),true);return{recoveryCodes};}
async disableTotp(userId:string,password:string,code:string){const u=await this.users.findById(userId);if(!u||!(await verifyPassword(password,u.passwordHash)))throw new UnauthorizedError('Invalid credentials');if(!u.totpEnabled||!u.totpSecretEncrypted)throw new ConflictError('Two-factor authentication is not enabled');if(!verifyTotp(decryptSecret(u.totpSecretEncrypted,this.env.AUTH_ENCRYPTION_KEY),code))throw new UnauthorizedError('Invalid verification code');await this.users.disableTotp(userId);}
private async createSession(userId:string,meta:{ip?:string;userAgent?:string}){const rawToken=randomToken(),csrfToken=randomToken(24),expiresAt=new Date(Date.now()+this.env.SESSION_TTL_HOURS*3600_000);const row=await this.sessions.create({userId,tokenHash:sha256(rawToken),csrfTokenHash:sha256(csrfToken),ip:meta.ip,userAgent:meta.userAgent?.slice(0,512),expiresAt});return{id:row.id,userId,csrfToken,expiresAt,rawToken};}
private async fail(u:User){const count=u.failedLoginCount+1,lock=count>=this.env.LOGIN_LOCKOUT_ATTEMPTS?new Date(Date.now()+this.env.LOGIN_LOCKOUT_MINUTES*60_000):null;await this.users.recordFailedLogin(u.id,lock?0:count,lock);}
private async verifySecondFactor(u:User,totp?:string,recovery?:string){if(totp&&u.totpSecretEncrypted&&verifyTotp(decryptSecret(u.totpSecretEncrypted,this.env.AUTH_ENCRYPTION_KEY),totp))return true;if(recovery){const wanted=hmac256(this.env.AUTH_RECOVERY_PEPPER,recovery),hashes=JSON.parse(u.recoveryCodeHashes||'[]') as string[],i=hashes.findIndex(h=>safeEqualHex(h,wanted));if(i>=0){hashes.splice(i,1);await this.users.updateRecoveryCodeHashes(u.id,JSON.stringify(hashes));return true;}}return false;}}
function toPublic(u:User):AuthenticatedUser{return{id:u.id,username:u.username,role:u.role,permissions:listPermissions(u.role),totpEnabled:u.totpEnabled};}
