import type { FastifyPluginAsync } from 'fastify';
import type { ZodTypeProvider } from 'fastify-type-provider-zod';
import { changePasswordSchema,disableTotpSchema,loginBodySchema,sessionIdParamsSchema,totpCodeSchema } from '../schemas/auth.js';

export const authRoutes:FastifyPluginAsync=async(fastify)=>{const app=fastify.withTypeProvider<ZodTypeProvider>();
 app.post('/api/auth/login',{config:{rateLimit:{max:5,timeWindow:'1 minute'}},schema:{body:loginBodySchema}},async(request,reply)=>{const result=await app.services.auth.login(request.body.username,request.body.password,request.body.totp,request.body.recoveryCode,{ip:request.ip,userAgent:request.headers['user-agent']});reply.setCookie(app.env.COOKIE_NAME,result.session.rawToken,{path:'/',httpOnly:true,secure:app.env.NODE_ENV==='production',sameSite:'strict',maxAge:app.env.SESSION_TTL_HOURS*3600,domain:app.env.COOKIE_DOMAIN});reply.setCookie(app.env.CSRF_COOKIE_NAME,result.session.csrfToken,{path:'/',httpOnly:false,secure:app.env.NODE_ENV==='production',sameSite:'strict',maxAge:app.env.SESSION_TTL_HOURS*3600,domain:app.env.COOKIE_DOMAIN});await app.services.audit.record({userId:result.user.id,action:'auth.login',ip:request.ip});return{user:result.user,expiresAt:result.session.expiresAt};});
 app.post('/api/auth/logout',{preHandler:[app.authenticate],config:{rateLimit:{max:20,timeWindow:'1 minute'}}},async(request,reply)=>{await app.services.auth.logout(request.auth!.session.id,request.auth!.user.id);reply.clearCookie(app.env.COOKIE_NAME,{path:'/',domain:app.env.COOKIE_DOMAIN});reply.clearCookie(app.env.CSRF_COOKIE_NAME,{path:'/',domain:app.env.COOKIE_DOMAIN});await app.services.audit.record({userId:request.auth!.user.id,action:'auth.logout',ip:request.ip});return{ok:true};});
 app.get('/api/auth/me',{preHandler:[app.authenticate]},async(request)=>({user:request.auth!.user,sessionExpiresAt:request.auth!.session.expiresAt}));
 app.post('/api/auth/password',{preHandler:[app.authenticate],config:{rateLimit:{max:5,timeWindow:'10 minutes'}},schema:{body:changePasswordSchema}},async(request)=>{await app.services.auth.changePassword(request.auth!.user.id,request.body.currentPassword,request.body.newPassword,request.auth!.session.id);await app.services.audit.record({userId:request.auth!.user.id,action:'auth.password.change',ip:request.ip});return{ok:true};});
 app.get('/api/auth/sessions',{preHandler:[app.authenticate]},async(request)=>({sessions:await app.services.auth.listSessions(request.auth!.user.id,request.auth!.session.id)}));
 app.delete('/api/auth/sessions/:sessionId',{preHandler:[app.authenticate],schema:{params:sessionIdParamsSchema}},async(request)=>({revoked:await app.services.auth.revokeSession(request.auth!.user.id,request.params.sessionId,request.auth!.session.id)}));
 app.post('/api/auth/sessions/revoke-others',{preHandler:[app.authenticate]},async(request)=>({revoked:await app.services.auth.revokeOtherSessions(request.auth!.user.id,request.auth!.session.id)}));
 app.post('/api/auth/2fa/setup',{preHandler:[app.authenticate],config:{rateLimit:{max:5,timeWindow:'10 minutes'}}},async(request)=>app.services.auth.beginTotp(request.auth!.user.id));
 app.post('/api/auth/2fa/confirm',{preHandler:[app.authenticate],schema:{body:totpCodeSchema}},async(request)=>{const result=await app.services.auth.confirmTotp(request.auth!.user.id,request.body.code);await app.services.audit.record({userId:request.auth!.user.id,action:'auth.2fa.enable',ip:request.ip});return result;});
 app.post('/api/auth/2fa/disable',{preHandler:[app.authenticate],schema:{body:disableTotpSchema}},async(request)=>{await app.services.auth.disableTotp(request.auth!.user.id,request.body.password,request.body.code);await app.services.audit.record({userId:request.auth!.user.id,action:'auth.2fa.disable',ip:request.ip});return{ok:true};});
};
