"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { ShieldCheck } from "lucide-react";
import { authApi } from "@/lib/api/auth";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
export default function LoginPage(){const router=useRouter();const[username,setUsername]=useState("admin"),[password,setPassword]=useState(""),[factor,setFactor]=useState(""),[useRecovery,setUseRecovery]=useState(false),[need2fa,setNeed2fa]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await authApi.login({username,password,...(need2fa?(useRecovery?{recoveryCode:factor}:{totp:factor}):{})});router.replace("/");router.refresh();}catch(cause){const text=cause instanceof Error?cause.message:"Login failed";if(text.toLowerCase().includes("two-factor")){setNeed2fa(true);setError("Enter your authenticator code or a recovery code.");}else setError(text);}finally{setBusy(false)}}return <main className="flex min-h-screen items-center justify-center bg-zinc-950 p-6"><Card className="w-full max-w-md space-y-6 p-7"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-500/10 p-2.5"><ShieldCheck className="h-6 w-6 text-emerald-400"/></div><div><h1 className="text-xl font-semibold">Sign in to 1315 Panel</h1><p className="text-sm text-zinc-400">1315 SMP administration</p></div></div><form onSubmit={submit} className="space-y-4"><Input value={username} onChange={(event)=>setUsername(event.target.value)} placeholder="Username" autoComplete="username" required/><Input type="password" value={password} onChange={(event)=>setPassword(event.target.value)} placeholder="Password" autoComplete="current-password" required/>{need2fa?<div className="space-y-2"><Input value={factor} onChange={(event)=>setFactor(event.target.value)} placeholder={useRecovery?"Recovery code":"6-digit authenticator code"} inputMode={useRecovery?undefined:"numeric"} required/><button type="button" onClick={()=>{setUseRecovery((value)=>!value);setFactor("");}} className="text-xs text-zinc-400 hover:text-zinc-200">{useRecovery?"Use authenticator code":"Use a recovery code"}</button></div>:null}{error?<p className="text-sm text-red-400">{error}</p>:null}<Button className="w-full" disabled={busy}>{busy?"Signing in…":"Sign in"}</Button></form></Card></main>}
